[package]
name = "png"
version = "0.1.0"
authors = ["Yuri Rider Sarah <yuri-rider-sarah@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
